label:
  en: Info
  nl: Info
icon: info
columns:
  info:
    width: 1/1
    sections:
      info:
        type: fields
        fields:
          updated_by:
            label: 
              nl: Laatst aangepast door
              en: Last updated by
              fr: Dernière mise à jour par
            type: users
            multiple: false
            default: true
            disabled: true
            width: 1/3
          updated_on:
            label: 
              nl: Laatste aangepast op
              en: Last updated on
              fr: Dernière mise à jour le
            type: date
            time: true
            calendar: false
            display: YYYY.MM.DD
            default: now
            disabled: true
            width: 1/3
          gap_1:
            type: gap
            width: 1/3
          created_by:
            label: 
              nl: Aangemaakt door
              en: Created by
              fr: Créé par
            type: users
            multiple: false
            default: true
            disabled: true
            width: 1/3
          created_on:
            label: 
              nl: Aangemaakt op
              en: Created on
              fr: Créé le
            type: date
            time: true
            calendar: false
            display: YYYY.MM.DD
            default: now
            disabled: true
            width: 1/3
          gap_2:
            type: gap
            width: 1/3
